apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: worker-log-size
spec:
  machineConfigPoolSelector:
    matchLabels:
      "pools.operator.machineconfiguration.openshift.io/worker": ""
  kubeletConfig:
    containerLogMaxSize: 200Mi
    containerLogMaxFiles: 10
